%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Volumes/BackupPlus/Information technology/DATA/GS_2007_2011.csv
%
% Auto-generated by MATLAB on 12-Sep-2021 10:06:26

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Date", "Open", "High", "Low", "Close", "AdjClose", "Volume"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Date", "InputFormat", "yyyy-MM-dd");

% Import the data
GS1 = readtable("/Volumes/BackupPlus/Information technology/DATA/GS.2007_2011.csv", opts);


%% Clear temporary variables
clear opts